D10_PLUME = 'classical_plume'
D10_EPS = 'classical_10d'
D15_EPS = 'classical_15d'

ALL_EPSGRAM = [D10_PLUME, D10_EPS, D15_EPS]
TIMEOUT_IN_SEC = 60 
STATION_SELECT_ONE_TIME, STATION_SELECT_SUBSCRIBE, ONE_TIME, SUBSCRIBE, UNSUBSCRIBE = range(
    5)
